import moment from 'moment';

const playersData = [
  {
    key: 1,
    order: 1,
    name: 'Hoang Xuan Truong',
    win: 0,
    lose: 0,
    streak: 0,
    bonus: 0,
    point: 0,
    level: 0,
  },
  {
    key: 2,
    order: 1,
    name: 'Someone else',
    win: 0,
    lose: 0,
    streak: 0,
    bonus: 0,
    point: 1,
    level: 0,
  },
];

const historyData = [
  {
    key: 1,
    datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 1',
    loser: 'Player 2',
    type: 'Bo1',
    streak: true,
    chain: 1,
    rank_diff: 1,
    bonus: 0,
    comment: 'Sth',
  },
  {
    key: 2,
    datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 3',
    loser: 'Player 2',
    type: 'Bo3',
    streak: false,
    chain: 0,
    rank_diff: 0,
    bonus: 0,
    comment: '',
  },
  {
    key: 1,
    datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 1',
    loser: 'Player 2',
    type: 'Bo1',
    streak: true,
    chain: 0,
    rank_diff: 0,
    bonus: 0,
    comment: '',
  },
  {
    key: 2,
    datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 3',
    loser: 'Player 2',
    type: 'Bo3',
    streak: false,
    chain: 0,
    rank_diff: 0,
    bonus: 0,
    comment: '',
  },
  {
    key: 1,
    datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 1',
    loser: 'Player 2',
    type: 'Bo1',
    streak: true,
    chain: 0,
    rank_diff: 0,
    bonus: 0,
    comment: '',
  },
  {
    key: 2,
    datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 3',
    loser: 'Player 2',
    type: 'Bo3',
    streak: false,
    chain: 0,
    rank_diff: 0,
    bonus: 0,
    comment: '',
  },
  {
    key: 1,
    datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 1',
    loser: 'Player 2',
    type: 'Bo1',
    streak: true,
    chain: 0,
    rank_diff: 0,
    bonus: 0,
    comment: '',
  },
  {
    key: 2,
    datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 3',
    loser: 'Player 2',
    type: 'Bo3',
    streak: false,
    chain: 0,
    rank_diff: 0,
    bonus: 0,
    comment: '',
  },
  {
    key: 1,
    datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 1',
    loser: 'Player 2',
    type: 'Bo1',
    streak: true,
    chain: 0,
    rank_diff: 0,
    bonus: 0,
    comment: '',
  },
  {
    key: 2,
    datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 3',
    loser: 'Player 2',
    type: 'Bo3',
    streak: false,
    chain: 0,
    rank_diff: 0,
    bonus: 0,
    comment: '',
  },
  {
    key: 1,
    datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 1',
    loser: 'Player 2',
    type: 'Bo1',
    streak: true,
    chain: 0,
    rank_diff: 0,
    bonus: 0,
    comment: '',
  },
  {
    key: 2,
    datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
    winner: 'Player 3',
    loser: 'Player 2',
    type: 'Bo3',
    streak: false,
    chain: 0,
    rank_diff: 0,
    bonus: 0,
    comment: '',
  },
];

const eventBonusData = [
  {
    key: 1,
    datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
    name: 'Player 1',
    bonus: 10,
    comment: 'Dep trai',
  },
];

export { playersData, historyData, eventBonusData };
