// import moment from 'moment';

const playersData = [
  // {
  //   key: 0,
  //   name: 'Hoang Xuan Truong',
  //   win: 0,
  //   lose: 0,
  //   streak: 2,
  //   bonus: 0,
  //   point: 0,
  //   level: 3,
  // },
  // {
  //   key: 1,
  //   name: 'Someone else',
  //   win: 0,
  //   lose: 0,
  //   streak: 0,
  //   bonus: 0,
  //   point: 10,
  //   level: 0,
  // },
  // {
  //   key: 2,
  //   name: 'Third else',
  //   win: 0,
  //   lose: 0,
  //   streak: 0,
  //   bonus: 0,
  //   point: 5,
  //   level: 0,
  // },
];

const historyData = [
  // {
  //   key: 0,
  //   datetime: moment('2013-02-09 09:30:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 1',
  //   loser: 'Player 2',
  //   type: 'Bo1',
  //   streak: true,
  //   chain: 1,
  //   rankDiff: 1,
  //   bonus: 0,
  //   comment: 'Sth',
  // },
  // {
  //   key: 1,
  //   datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 3',
  //   loser: 'Player 2',
  //   type: 'Bo3',
  //   streak: false,
  //   chain: 0,
  //   rankDiff: 0,
  //   bonus: 0,
  //   comment: '',
  // },
  // {
  //   key: 2,
  //   datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 1',
  //   loser: 'Player 2',
  //   type: 'Bo1',
  //   streak: true,
  //   chain: 0,
  //   rankDiff: 0,
  //   bonus: 0,
  //   comment: '',
  // },
  // {
  //   key: 3,
  //   datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 3',
  //   loser: 'Player 2',
  //   type: 'Bo3',
  //   streak: false,
  //   chain: 0,
  //   rankDiff: 0,
  //   bonus: 0,
  //   comment: '',
  // },
  // {
  //   key: 4,
  //   datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 1',
  //   loser: 'Player 2',
  //   type: 'Bo1',
  //   streak: true,
  //   chain: 0,
  //   rankDiff: 0,
  //   bonus: 0,
  //   comment: '',
  // },
  // {
  //   key: 5,
  //   datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 3',
  //   loser: 'Player 2',
  //   type: 'Bo3',
  //   streak: false,
  //   chain: 0,
  //   rankDiff: 0,
  //   bonus: 0,
  //   comment: '',
  // },
  // {
  //   key: 6,
  //   datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 1',
  //   loser: 'Player 2',
  //   type: 'Bo1',
  //   streak: true,
  //   chain: 0,
  //   rankDiff: 0,
  //   bonus: 0,
  //   comment: '',
  // },
  // {
  //   key: 7,
  //   datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 3',
  //   loser: 'Player 2',
  //   type: 'Bo3',
  //   streak: false,
  //   chain: 0,
  //   rankDiff: 0,
  //   bonus: 0,
  //   comment: '',
  // },
  // {
  //   key: 8,
  //   datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 1',
  //   loser: 'Player 2',
  //   type: 'Bo1',
  //   streak: true,
  //   chain: 0,
  //   rankDiff: 0,
  //   bonus: 0,
  //   comment: '',
  // },
  // {
  //   key: 9,
  //   datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 3',
  //   loser: 'Player 2',
  //   type: 'Bo3',
  //   streak: false,
  //   chain: 0,
  //   rankDiff: 0,
  //   bonus: 0,
  //   comment: '',
  // },
  // {
  //   key: 10,
  //   datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 1',
  //   loser: 'Player 2',
  //   type: 'Bo1',
  //   streak: true,
  //   chain: 0,
  //   rankDiff: 0,
  //   bonus: 0,
  //   comment: '',
  // },
  // {
  //   key: 11,
  //   datetime: moment('2013-02-08 09:31:26', 'YYYY-MM-DD H:m:s'),
  //   winner: 'Player 3',
  //   loser: 'Player 2',
  //   type: 'Bo3',
  //   streak: false,
  //   chain: 0,
  //   rankDiff: 0,
  //   bonus: 0,
  //   comment: '',
  // },
];

const eventBonusData = [
  // {
  //   key: 0,
  //   datetime: moment('2013-02-08 09:30:26', 'YYYY-MM-DD H:m:s'),
  //   name: 'Player 1',
  //   bonus: 10,
  //   comment: 'Dep trai',
  // },
  // {
  //   key: 1,
  //   datetime: moment('2013-02-09 09:30:26', 'YYYY-MM-DD H:m:s'),
  //   name: 'Player 1',
  //   bonus: 10,
  //   comment: 'Dep trai',
  // },
];

export { playersData, historyData, eventBonusData };
